# Generated by Django 2.1.15 on 2020-02-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Indirizzo e-mail')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome')),
                ('cognome', models.CharField(blank=True, max_length=255, verbose_name='Cognome')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('citta', models.CharField(blank=True, max_length=255, verbose_name='Città')),
                ('provincia_estero', models.CharField(blank=True, max_length=255, verbose_name='Provincia estero')),
                ('stato', models.CharField(blank=True, choices=[('I', 'Italia'), ('E', 'Estero')], max_length=2, verbose_name='Stato')),
                ('stato_estero', models.CharField(blank=True, max_length=255, verbose_name='Altro stato')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='provincia_ita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
